# database
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  motoserver:
    image: motoserver/moto:latest
    ports:
      - "3001:3000"
    environment:
      - MOTO_PORT=3000 # set moto listener port with env var